server:
  ssl:
    key-store: ../triela-private/triela.ml/triela.pkcs12
    #key-store-password: [from triela-private]
    keyStoreType: PKCS12
    keyAlias: triela
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:63306/imageuploader?characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: 1qaz2wsx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  thymeleaf:
    cache: false
  resources:
    static-locations:
      - file:./src/main/resources/static/
      - classpath:/static/
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
